datadeling/datafabrikken-portal

package-lock.json, package.json, src/components/header/index.tsx, src/components/header/styled.ts
=> feat: mobile menu

src/entrypoints/main/router/pages/datasets-page/index.tsx
=> chore: only show results when query or theme is used

src/components/info-box/components/info-box-image/index.tsx, src/components/info-box/components/info-box/index.tsx, src/components/info-box/components/info-box/styled.ts, src/components/info-box/index.ts, src/entrypoints/main/router/pages/main-page/index.tsx, src/entrypoints/main/router/pages/news-page/index.tsx, src/services/api/cms-api/news.ts, src/types/domain.d.ts
=> chore: display social media image

src/components/community/tag/index.tsx, src/components/community/tag/styled.ts, src/components/community/topic/index.tsx, src/components/community/topic/styled.ts, src/components/community/user/index.tsx, src/components/community/user/styled.ts, src/components/with-community-search/index.tsx, src/components/with-community-search/redux/action-types.ts, src/components/with-community-search/redux/actions.ts, src/components/with-community-search/redux/reducer.ts, src/components/with-community-search/redux/saga.ts, src/entrypoints/main/redux/reducer.ts, src/entrypoints/main/redux/saga.ts, src/entrypoints/main/router/pages/details-page-dataset/index.tsx, src/l10n/nb.json, src/services/api/community-api/search.ts
=> feat: adds mentioned in community component

src/components/icons/spinner-icon/index.tsx, src/components/icons/spinner-icon/styled.ts, src/entrypoints/main/router/pages/organization-page/index.tsx, src/entrypoints/main/router/pages/organization-page/styled.ts, src/entrypoints/main/router/pages/organizations-page/index.tsx, src/entrypoints/main/router/pages/organizations-page/styled.ts, src/images/spinner.inline.svg
=> feat: adds loading spinner for organizations pages

src/components/details-page/components/content-section/styled.ts, src/components/details-page/components/metadata-quality/styled.ts, src/components/details-page/styled.ts, src/components/info-box/components/info-box/styled.ts, src/components/rounded-tag/styled.ts, src/components/search-hit/styled.ts, src/entrypoints/main/router/pages/datasets-page/components/filters/styled.ts, src/entrypoints/main/router/pages/datasets-page/index.tsx, src/entrypoints/main/router/pages/datasets-page/styled.ts, src/entrypoints/main/router/pages/details-page-dataset/components/dataset-distribution/components/dataset-distribution/styled.ts, src/entrypoints/main/router/pages/main-page/index.tsx
=> chore: minor mobile view changes

src/entrypoints/main/router/pages/datasets-page/index.tsx, src/entrypoints/main/router/pages/datasets-page/styled.ts, src/l10n/nb.json
=> feat: adds community route on no search hits

src/components/radio-options/index.tsx, src/components/radio-options/styled.ts, src/entrypoints/main/router/pages/datasets-page/components/filters/index.tsx, src/entrypoints/main/router/pages/datasets-page/index.tsx, src/utils/location-helper/index.ts
=> feat: adds radio option for access rights

package-lock.json, src/entrypoints/main/router/pages/community-categories-page/components/category/index.tsx, src/entrypoints/main/router/pages/community-categories-page/components/category/styled.ts, src/entrypoints/main/router/pages/community-topic-page/components/post/styled.ts, src/entrypoints/main/router/pages/community-topics-page/components/topic/styled.ts
=> chore: replace post with topic title

src/entrypoints/main/router/pages/details-page-dataset/index.tsx, src/types/domain.d.ts
=> fix: remove null relations

src/entrypoints/main/router/pages/community-categories-page/components/category/index.tsx, src/entrypoints/main/router/pages/community-categories-page/components/category/styled.ts, src/images/icon-community-insight.inline.svg, src/images/icon-law.inline.svg
=> chore: add law icon and fix insight icon

src/entrypoints/main/router/pages/community-topics-page/index.tsx
=> fix: load on sort state change

package-lock.json, src/entrypoints/main/router/pages/details-page-dataset/components/dataset-distribution/components/detail/styled.ts, src/entrypoints/main/router/pages/organization-page/styled.ts, src/entrypoints/main/router/pages/organizations-page/styled.ts
=> chore: improved mobile view dataset detail page

src/components/header/index.tsx, src/entrypoints/main/router/pages/courses-page/components/course-card/styled.ts, src/images/course-wiggly-line.inline.svg
=> fix: mobile view, background color

.github/workflows/deploy-prod.yaml, .github/workflows/deploy-staging.yaml, src/entrypoints/main/router/pages/datasets-page/index.tsx
=> fix: broken link

src/components/article/styled.ts
=> fix: element moved inside div, updated styles

package-lock.json, src/entrypoints/main/router/pages/community-topic-page/styled.ts, src/entrypoints/main/router/pages/community-topics-page/components/topic/index.tsx, src/entrypoints/main/router/pages/community-topics-page/components/topic/styled.ts, src/images/icon-pinned.inline.svg
=> feat: show pinned topics

package-lock.json, package.json, src/components/with-datasets/index.tsx, src/components/with-datasets/redux/reducer.ts, src/entrypoints/main/router/pages/datasets-page/index.tsx
=> fix: updated react-paginate and use totalPages

package-lock.json, src/components/community/calendar-date/index.tsx, src/components/community/calendar-date/styled.ts, src/components/community/user/index.tsx, src/entrypoints/main/router/pages/community-topic-page/components/post/index.tsx, src/entrypoints/main/router/pages/community-topic-page/components/post/styled.ts, src/entrypoints/main/router/pages/community-topics-page/components/topic/index.tsx, src/images/icon-calendar-small.inline.svg, src/types/domain.d.ts, src/types/enums.ts, src/utils/community/utils.ts
=> chore: parse calendar plugin tags

Dockerfile, nginx.conf, package-lock.json, package.json, sitemap-builder.ts, sitemap/robots.txt, sitemap/sitemap.xml, src/entrypoints/main/router/routes/index.tsx, src/routes.ts, tsconfig.sitemap.json
=> chore: generate sitemap and add robots.txt

sitemap/sitemap.xml, src/routes.ts
=> fix: added missing routes

src/entrypoints/main/router/pages/community-topic-page/components/post/styled.ts
Fixes #informasjonsforvaltning/fdk-issue-tracker#491
=> fix: link style in post

package-lock.json, package.json, src/l10n/nb.json
=> update access rights terms

src/entrypoints/main/index.html
Part of Informasjonsforvaltning/fdk-issue-tracker#499
=> feat: adds preview image

.gitattributes, src/entrypoints/main/router/pages/contact-page/index.tsx, src/entrypoints/main/router/pages/contact-page/styled.ts, src/services/api/generated/cms/graphql.ts, src/services/api/strapi/graphql/contact.graphql
=> feat: use strapi for contact page

src/components/breadcrumbs/index.tsx, src/components/breadcrumbs/strapi-article-breadcrumb/index.tsx, src/entrypoints/main/router/pages/article-page-strapi/articles.ts, src/entrypoints/main/router/pages/article-page-strapi/index.tsx, src/entrypoints/main/router/pages/article-page-strapi/styled.ts, src/enums/index.ts, src/l10n/nb.json, src/routes.ts, src/services/api/generated/cms/graphql.ts, src/services/api/strapi/graphql/fancy-article.graphql, src/utils/strapi/index.ts
=> feat: adds strapi article page

src/entrypoints/main/router/pages/details-page-dataset/components/dataset-distribution/components/dataset-distribution/index.tsx, src/entrypoints/main/router/pages/details-page-dataset/components/dataset-distribution/components/summary/index.tsx, src/entrypoints/main/router/pages/details-page-dataset/components/dataset-distribution/components/summary/styled.ts
Part of Informasjonsforvaltning/fdk-issue-tracker#548
=> feat: adds download icon to distribution summary

src/services/api/generated/cms/graphql.ts, src/services/api/strapi/graphql/course.graphql, src/services/api/strapi/graphql/guidance.graphql
=> feat: sort by position

src/components/article/styled.ts, src/entrypoints/main/router/pages/article-page-strapi/index.tsx, src/entrypoints/main/router/pages/article-page-strapi/styled.ts, src/services/api/generated/cms/graphql.ts, src/services/api/strapi/graphql/fancy-article.graphql
Closes Informasjonsforvaltning/fdk-issue-tracker#551
=> feat: updates strapi article page design

src/components/community/comments/components/comment-card/styled.ts, src/entrypoints/main/router/pages/community-topic-page/components/post/styled.ts
=> fix: bullets in ul in community posts

src/components/details-page/components/themes/index.tsx
=> fix: de duplicate eu themes

src/entrypoints/main/router/pages/community-topic-page/components/post/styled.ts
=> style: minor change

src/components/breadcrumbs/index.tsx, src/components/community/menu/index.tsx, src/components/community/menu/styled.ts, src/components/community/search-topic/index.tsx, src/components/community/search-topic/styled.ts, src/components/truncated-text/index.tsx, src/entrypoints/main/redux/reducer.ts, src/entrypoints/main/router/pages/community-search-page/index.tsx, src/entrypoints/main/router/pages/community-search-page/styled.ts, src/entrypoints/main/router/routes/index.tsx, src/enums/index.ts, src/l10n/nb.json, src/routes.ts, src/services/api/community-api/community-search.ts, src/types/domain.d.ts, src/utils/community/utils.ts
=> Add community search page

src/entrypoints/main/router/pages/community-categories-page/index.tsx, src/entrypoints/main/router/pages/community-categories-page/styled.ts
=> feat: show latest topics

src/components/details-page/index.tsx, src/components/with-reference-data/redux/actions.ts, src/components/with-reference-data/redux/reducer.ts, src/components/with-reference-data/redux/saga.ts, src/entrypoints/main/router/pages/datasets-page/index.tsx, src/entrypoints/main/router/pages/details-page-dataset/index.tsx, src/types/domain.d.ts
=> fix: change name reference-types and remove unused reference data

src/entrypoints/main/router/pages/community-topic-page/components/post/styled.ts
Fixes https://github.com/datadeling/behov-issue-tracker/issues/179
Fixes https://github.com/datadeling/behov-issue-tracker/issues/178
=> fix: display code

src/entrypoints/main/router/pages/datasets-page/index.tsx, src/utils/analytics/index.ts
=> feat: add ga4 text-search event
